import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,Bot,Check,RotateCcw,X} from "lucide-react";
import {Message,MessageContent,MessageResponse} from "@/components/ai-elements/message";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Input,Textarea} from "@/components/ui/input";
import {PageHeader} from "@/components/ui/page-header";
import {IntakeActionForm} from "@/features/ai-intake/components/intake-action-form";
import {serviceRequestReferenceSchema} from "@/features/service-requests/schemas";
import {resolveAiIntakeFactAction,sendAiIntakeMessageAction,startAiIntakeAction} from "@/server/actions/ai-intake";
import {getAiIntake} from "@/server/ai-intake/service";

const statusLabels={suggested:"À confirmer",confirmed:"Confirmé",conflicted:"Contradiction",rejected:"Rejeté",superseded:"Remplacé"} as const;
export default async function AiIntakePage({params}:{params:Promise<{organizationSlug:string;reference:string}>}){const {organizationSlug,reference:raw}=await params;const parsed=serviceRequestReferenceSchema.safeParse(raw);if(!parsed.success)notFound();const reference=parsed.data;const data=await getAiIntake(organizationSlug,reference);return <main className="mx-auto grid w-full max-w-[var(--content-max)] gap-6 p-4 sm:p-8"><PageHeader eyebrow={<Button asChild variant="link"><Link href={`/app/${organizationSlug}/dossiers/${reference}`}><ArrowLeft/>Retour au Dossier</Link></Button>} title="Assistant de qualification" description="Compréhension et extraction internes. Les règles déterministes et la validation humaine restent prioritaires."/>
  {!data.schema?<Card className="hover:translate-y-0"><CardContent className="pt-6 text-sm text-muted-foreground">Associez un Playbook publié au Dossier avant de démarrer AI Intake.</CardContent></Card>:!data.session?<Card className="hover:translate-y-0"><CardHeader><Bot className="size-5 text-primary"/><CardTitle>Démarrer une session privée</CardTitle><CardDescription>Aucun lien public ne sera créé. La locale du Dossier sera utilisée.</CardDescription></CardHeader><CardContent><IntakeActionForm action={startAiIntakeAction.bind(null,organizationSlug,reference)} label="Démarrer AI Intake"/></CardContent></Card>:<div className="grid gap-6 xl:grid-cols-[1fr_24rem]"><div className="grid gap-6"><Card className="hover:translate-y-0"><CardHeader><CardTitle>Conversation interne</CardTitle><CardDescription>Les messages sont ordonnés et immuables. Le contexte fournisseur est limité aux six messages récents.</CardDescription></CardHeader><CardContent className="grid gap-5"><div className="grid max-h-[32rem] gap-5 overflow-y-auto" aria-live="polite">{data.messages.map(message=><Message key={message.id} from={message.role==="user"?"user":"assistant"}><MessageContent>{message.role==="assistant"?<MessageResponse>{message.content}</MessageResponse>:<p>{message.content}</p>}</MessageContent></Message>)}{!data.messages.length?<p className="text-sm text-muted-foreground">Aucun message pour le moment.</p>:null}</div><IntakeActionForm action={sendAiIntakeMessageAction.bind(null,organizationSlug,reference)} label="Analyser le message"><input type="hidden" name="requestId" value={crypto.randomUUID()}/><Textarea name="message" required maxLength={5000} placeholder="Collez ou saisissez la demande libre du prospect…"/><p className="text-xs text-muted-foreground">En cas d’indisponibilité IA, le message est conservé sans modifier les faits.</p></IntakeActionForm></CardContent></Card>
    <Card className="hover:translate-y-0"><CardHeader><CardTitle>Ce que Qualifyr a compris</CardTitle><CardDescription>La confiance indique une suggestion, jamais une vérité absolue.</CardDescription></CardHeader><CardContent className="grid gap-4">{data.facts.filter(f=>f.status!=="superseded").map(fact=>{const field=data.schema?.fields.find(f=>f.key===fact.field_key);return <article key={fact.id} className="grid gap-3 rounded-[var(--radius-lg)] border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{field?.label??fact.field_key}</p><Badge variant={fact.status==="confirmed"?"success":fact.status==="conflicted"?"warning":"neutral"}>{statusLabels[fact.status]}</Badge></div><p className="text-sm">{String(fact.value)}</p><p className="text-xs text-muted-foreground">Source : {fact.source_type==="manual"?"correction humaine":"extraction IA"} · confiance indicative {Math.round(Number(fact.confidence)*100)} %</p>{["suggested","conflicted"].includes(fact.status)?<div className="grid gap-3 sm:grid-cols-3"><IntakeActionForm action={resolveAiIntakeFactAction.bind(null,organizationSlug,reference)} label="Confirmer" variant="outline"><input type="hidden" name="factId" value={fact.id}/><input type="hidden" name="action" value="confirm"/></IntakeActionForm><IntakeActionForm action={resolveAiIntakeFactAction.bind(null,organizationSlug,reference)} label="Rejeter" variant="destructive"><input type="hidden" name="factId" value={fact.id}/><input type="hidden" name="action" value="reject"/></IntakeActionForm><IntakeActionForm action={resolveAiIntakeFactAction.bind(null,organizationSlug,reference)} label="Corriger" variant="outline"><input type="hidden" name="factId" value={fact.id}/><input type="hidden" name="action" value="correct"/><Input name="value" required defaultValue={String(fact.value)} aria-label={`Correction de ${field?.label??fact.field_key}`}/></IntakeActionForm></div>:null}</article>;})}{!data.facts.length?<p className="text-sm text-muted-foreground">Aucun fait extrait.</p>:null}</CardContent></Card></div>
    <div className="grid h-fit gap-6 xl:sticky xl:top-24"><Card className="hover:translate-y-0"><CardHeader><CardTitle>Service probable</CardTitle></CardHeader><CardContent><p className="text-sm">{data.services.find(service=>service.id===data.session.detected_service_definition_id)?.name??"À préciser"}</p>{data.session.service_confidence!==null?<p className="mt-1 text-xs text-muted-foreground">Confiance indicative {Math.round(Number(data.session.service_confidence)*100)} %, sans association automatique.</p>:null}</CardContent></Card><Card className="hover:translate-y-0"><CardHeader><CardTitle>Prochaine question</CardTitle></CardHeader><CardContent><p className="text-sm">{data.session.next_question??"Envoyez un message pour calculer la prochaine question."}</p></CardContent></Card><Card className="hover:translate-y-0"><CardHeader><CardTitle>Qualification</CardTitle></CardHeader><CardContent className="grid gap-3"><Badge variant={data.result?.recommended_status==="needs_review"?"warning":"neutral"}>{data.result?.recommended_status??"non calculée"}</Badge><p className="text-xs text-muted-foreground">Une preuve annoncée ne compte jamais comme reçue. AI Intake ne qualifie jamais automatiquement.</p><Button asChild variant="outline"><Link href={`/app/${organizationSlug}/dossiers/${reference}/qualification`}><RotateCcw/>Voir la qualification</Link></Button></CardContent></Card>{data.executions.length?<Card className="hover:translate-y-0"><CardHeader><CardTitle>Exécutions minimisées</CardTitle></CardHeader><CardContent><ul className="grid gap-2 text-xs">{data.executions.map(run=><li key={run.id} className="flex items-center gap-2">{run.status==="succeeded"?<Check className="size-3 text-success"/>:<X className="size-3 text-destructive"/>}<span>{run.provider} · {run.status} · {run.latency_ms??0} ms</span></li>)}</ul></CardContent></Card>:null}</div></div>}
  </main>;}
