begin;
select plan(18);
select has_table('public','hub_module_definitions','module catalog exists');
select has_table('public','organization_hub_modules','organization module installations exist');
select has_table('public','hub_event_log','event log exists');
select has_table('public','organization_hub_integrations','organization integrations exist');
select policies_are('public','organization_hub_modules',array['members read installed hub modules'],'module mutations are not direct policies');
select policies_are('public','organization_hub_agents',array['members read installed hub agents'],'agent mutations are not direct policies');
select policies_are('public','organization_hub_integrations',array['members read configured hub integrations'],'integration mutations are not direct policies');
select function_privs_are('public','manage_hub_module',array['uuid','text','text','jsonb'],'anon',array[]::text[],'anonymous users cannot manage modules');
select function_privs_are('public','manage_hub_agent',array['uuid','text','text','jsonb'],'anon',array[]::text[],'anonymous users cannot manage agents');
select function_privs_are('public','manage_hub_integration',array['uuid','text','text','jsonb'],'anon',array[]::text[],'anonymous users cannot manage integrations');
select function_privs_are('public','apply_hub_pack',array['uuid','text'],'anon',array[]::text[],'anonymous users cannot apply packs');
select ok((select relforcerowsecurity from pg_class where oid='public.organization_hub_modules'::regclass),'module RLS is forced');
select ok((select relforcerowsecurity from pg_class where oid='public.organization_hub_agents'::regclass),'agent RLS is forced');
select ok((select relforcerowsecurity from pg_class where oid='public.organization_hub_integrations'::regclass),'integration RLS is forced');
select ok((select relforcerowsecurity from pg_class where oid='public.hub_event_log'::regclass),'event RLS is forced');
select ok((select count(*) from public.hub_agent_definitions)=8,'eight agent registry entries are seeded');
select ok((select count(*) from public.hub_pack_definitions)=5,'five business packs are seeded');
select ok((select count(*) from public.hub_integration_definitions)>=13,'integration registry is seeded');
select * from finish(); rollback;
