import "server-only";

import {notFound} from "next/navigation";
import {playbookSchema} from "@/features/playbooks/schemas";
import type {PlaybookSchema} from "@/features/playbooks/types";
import {createClient} from "@/lib/supabase/server";
import {requireServiceRequestContext,getServiceRequestForOrganization} from "@/server/service-requests/service";

export async function listServices(organizationSlug:string){const context=await requireServiceRequestContext(organizationSlug);const supabase=await createClient();const [{data:services,error},{data:coverage,error:coverageError}]=await Promise.all([supabase.from("service_definitions").select("id,code,name,description,status,created_at").eq("organization_id",context.organization.id).order("name"),supabase.from("coverage_areas").select("id,service_definition_id,area_type,country_code,value").eq("organization_id",context.organization.id).order("created_at")]);if(error||coverageError)throw new Error("services_unavailable");return {context,services:services??[],coverage:coverage??[]};}

export async function listPlaybooks(organizationSlug:string){const context=await requireServiceRequestContext(organizationSlug);const supabase=await createClient();const [{data:playbooks,error},{data:versions,error:versionError},{data:services,error:serviceError}]=await Promise.all([supabase.from("playbooks").select("id,service_definition_id,code,name,description,status,active_version_id,created_at,updated_at").eq("organization_id",context.organization.id).order("updated_at",{ascending:false}),supabase.from("playbook_versions").select("id,playbook_id,version_number,status,published_at,lock_version").eq("organization_id",context.organization.id).order("version_number",{ascending:false}),supabase.from("service_definitions").select("id,name,status").eq("organization_id",context.organization.id).order("name")]);if(error||versionError||serviceError)throw new Error("playbooks_unavailable");return {context,playbooks:playbooks??[],versions:versions??[],services:services??[]};}

export async function getPlaybook(organizationSlug:string,playbookId:string){const bundle=await listPlaybooks(organizationSlug);const playbook=bundle.playbooks.find(item=>item.id===playbookId);if(!playbook)notFound();const supabase=await createClient();const {data,error}=await supabase.from("playbook_versions").select("id,playbook_id,version_number,status,schema_definition,published_at,lock_version").eq("organization_id",bundle.context.organization.id).eq("playbook_id",playbookId).order("version_number",{ascending:false});if(error)throw new Error("playbook_unavailable");const versions=(data??[]).map(version=>{const parsed=playbookSchema.safeParse(version.schema_definition);if(!parsed.success)throw new Error("invalid_playbook_schema");return {...version,schema:parsed.data};});return {...bundle,playbook,versions};}

export async function listPublishedPlaybookVersions(organizationId:string){const supabase=await createClient();const [{data:versions,error},{data:playbooks,error:playbookError}]=await Promise.all([supabase.from("playbook_versions").select("id,playbook_id,version_number").eq("organization_id",organizationId).eq("status","published").order("version_number",{ascending:false}),supabase.from("playbooks").select("id,name,service_definition_id").eq("organization_id",organizationId).eq("status","active")]);if(error||playbookError)throw new Error("playbook_versions_unavailable");return (versions??[]).map(version=>{const playbook=playbooks?.find(item=>item.id===version.playbook_id);return {id:version.id,versionNumber:version.version_number,playbookName:playbook?.name??"Playbook",serviceDefinitionId:playbook?.service_definition_id??""};});}

export async function getDossierQualification(organizationSlug:string,reference:string){const dossierBundle=await getServiceRequestForOrganization(organizationSlug,reference);const supabase=await createClient();const publishedVersions=await listPublishedPlaybookVersions(dossierBundle.context.organization.id);let schema:PlaybookSchema|null=null;let version:null|{id:string;version_number:number;playbook_id:string}=null;let playbookName:string|null=null;if(dossierBundle.detail.playbookVersionId){const {data,error}=await supabase.from("playbook_versions").select("id,version_number,playbook_id,schema_definition").eq("organization_id",dossierBundle.context.organization.id).eq("id",dossierBundle.detail.playbookVersionId).maybeSingle();if(error)throw new Error("qualification_unavailable");if(data){const parsed=playbookSchema.safeParse(data.schema_definition);if(!parsed.success)throw new Error("invalid_playbook_schema");schema=parsed.data;version={id:data.id,version_number:data.version_number,playbook_id:data.playbook_id};const {data:playbook}=await supabase.from("playbooks").select("name").eq("organization_id",dossierBundle.context.organization.id).eq("id",data.playbook_id).maybeSingle();playbookName=playbook?.name??null;}}
  const {data:result,error:resultError}=await supabase.from("qualification_results").select("id,field_values,evidence_values,required_fields_completed,required_fields_total,proofs_received,proofs_expected,missing_information,passed_rules,failed_rules,human_validation_required,recommended_status,next_action,evaluation_version,evaluated_at,validated_at,validated_by").eq("organization_id",dossierBundle.context.organization.id).eq("service_request_id",dossierBundle.detail.id).maybeSingle();if(resultError)throw new Error("qualification_unavailable");return {...dossierBundle,publishedVersions,schema,version,playbookName,result};}
