import { Blocks, BrainCircuit, Cable, Code2, PackageCheck, Settings2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { HubActionForm } from "@/features/hub/components/action-form";
import { hubMessages } from "@/features/hub/messages";
import { canManageHub } from "@/features/hub/permissions";
import { manageHubAgentAction, applyHubPackAction, manageHubIntegrationAction, manageHubModuleAction } from "@/server/actions/hub";
import { getHub } from "@/server/hub/service";

const catalogVariant=(status:string)=>status==="available"?"success":status==="planned"?"neutral":"danger";
const installationVariant=(status:string)=>status==="active"?"success":status==="disabled"?"warning":"neutral";
export default async function HubPage({params}:{params:Promise<{organizationSlug:string}>}){const {organizationSlug}=await params;const hub=await getHub(organizationSlug);const canManage=canManageHub(hub.context.role);const modules=new Map(hub.installedModules.map(item=>[item.module_definition_id,item.status]));const agents=new Map(hub.installedAgents.map(item=>[item.agent_definition_id,item.status]));const integrations=new Map(hub.installedIntegrations.map(item=>[item.integration_definition_id,item.status]));const activePack=hub.installedPacks.find(item=>item.status==="active");return <main className="mx-auto grid w-full max-w-[var(--content-max)] gap-6 p-4 sm:p-8"><PageHeader eyebrow={<Badge variant="success">Interne</Badge>} title={hubMessages.title} description={hubMessages.description}/>
<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Blocks} label="Modules actifs" value={[...modules.values()].filter(x=>x==="active").length}/><Metric icon={BrainCircuit} label="Agents actifs" value={[...agents.values()].filter(x=>x==="active").length}/><Metric icon={Cable} label="Intégrations configurées" value={[...integrations.values()].filter(x=>x==="configured").length}/><Metric icon={PackageCheck} label="Pack actif" value={activePack?1:0}/></div>
<HubSection id="modules" icon={Blocks} title="Modules" description="Manifestes internes uniquement : les modules prévus ne créent aucune fonctionnalité métier."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{hub.modules.map(item=>{const status=modules.get(item.id);return <Card key={item.id} className="hover:translate-y-0"><CardHeader><div className="flex items-start justify-between gap-2"><div><CardTitle>{item.name}</CardTitle><CardDescription>v{item.version} · {item.category}</CardDescription></div><Badge variant={status?installationVariant(status):catalogVariant(item.catalog_status)}>{status?hubMessages.module[status as keyof typeof hubMessages.module]:hubMessages.catalog[item.catalog_status as keyof typeof hubMessages.catalog]}</Badge></div><CardDescription>{item.description}</CardDescription></CardHeader><CardContent className="grid gap-3"><p className="text-xs text-muted-foreground">Dépendances : {(item.dependencies as string[]).length?(item.dependencies as string[]).join(", "):"Aucune"}</p>{canManage?<ModuleAction slug={organizationSlug} identifier={item.identifier} status={status}/>:null}</CardContent></Card>;})}</div></HubSection>
<HubSection id="packs" icon={PackageCheck} title="Packs métier" description="Changer de pack ajoute ou actualise les entrées du registre ; aucune donnée utilisateur n’est supprimée."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{hub.packs.map(item=><Card key={item.id} className="hover:translate-y-0"><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle>{item.name}</CardTitle><Badge variant={activePack?.pack_definition_id===item.id?"success":"neutral"}>{activePack?.pack_definition_id===item.id?"Actif":`v${item.version}`}</Badge></div><CardDescription>{item.description}</CardDescription></CardHeader><CardContent className="grid gap-3"><p className="text-xs text-muted-foreground">Modules : {(item.module_identifiers as string[]).join(", ")}</p>{canManage?<HubActionForm action={applyHubPackAction.bind(null,organizationSlug)} label="Appliquer ce pack"><input type="hidden" name="code" value={item.code}/></HubActionForm>:null}</CardContent></Card>)}</div></HubSection>
<HubSection id="agents" icon={BrainCircuit} title="Agents IA" description="Le Hub déclare les permissions, outils et politiques futures ; il ne lance aucun agent."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{hub.agents.map(item=>{const status=agents.get(item.id);return <Card key={item.id} className="hover:translate-y-0"><CardHeader><div className="flex items-start justify-between gap-2"><CardTitle className="text-base">{item.name}</CardTitle><Badge variant={status?installationVariant(status):catalogVariant(item.catalog_status)}>{status?hubMessages.module[status as keyof typeof hubMessages.module]:hubMessages.catalog[item.catalog_status as keyof typeof hubMessages.catalog]}</Badge></div><CardDescription>{item.description}</CardDescription></CardHeader>{canManage?<CardContent><AgentAction slug={organizationSlug} identifier={item.identifier} status={status}/></CardContent>:null}</Card>;})}</div></HubSection>
<HubSection id="integrations" icon={Cable} title="Intégrations" description="Aucun connecteur, jeton ou appel externe n’est créé. Les secrets sont explicitement refusés."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{hub.integrations.map(item=>{const status=integrations.get(item.id);return <Card key={item.id} className="hover:translate-y-0"><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle>{item.name}</CardTitle><Badge variant={status?installationVariant(status):catalogVariant(item.catalog_status)}>{status?hubMessages.integration[status as keyof typeof hubMessages.integration]:hubMessages.catalog[item.catalog_status as keyof typeof hubMessages.catalog]}</Badge></div><CardDescription>{item.description}</CardDescription></CardHeader>{canManage?<CardContent><IntegrationAction slug={organizationSlug} identifier={item.identifier} status={status}/></CardContent>:null}</Card>;})}</div></HubSection>
<div className="grid gap-6 xl:grid-cols-2"><Card className="hover:translate-y-0"><CardHeader><Code2 className="size-5 text-primary"/><CardTitle>API interne et Event Bus</CardTitle><CardDescription>Chaque mutation Hub émet un événement minimal, tenant-scopé et historisé. Aucune API publique ni code tiers ne sont exposés.</CardDescription></CardHeader><CardContent>{hub.events.length?<ul className="grid gap-2 text-sm">{hub.events.map(event=><li key={event.id} className="rounded-[var(--radius-sm)] border border-border px-3 py-2"><span className="font-mono text-primary">{event.event_kind}</span><span className="text-muted-foreground"> · {event.subject_identifier}</span></li>)}</ul>:<p className="text-sm text-muted-foreground">Aucun événement Hub pour cette organisation.</p>}</CardContent></Card><Card className="hover:translate-y-0"><CardHeader><Settings2 className="size-5 text-primary"/><CardTitle>Paramètres avancés</CardTitle><CardDescription>Manifestes, dépendances, compatibilités et permissions sont centralisés. Les secrets, clés API et code arbitraire ne sont jamais stockés.</CardDescription></CardHeader></Card></div></main>}
function Metric({icon:Icon,label,value}:{icon:typeof Blocks;label:string;value:number}){return <Card className="hover:translate-y-0"><CardContent className="flex items-center gap-3 pt-6"><Icon className="size-5 text-primary"/><div><p className="text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div></CardContent></Card>}
function HubSection({id,icon:Icon,title,description,children}:{id:string;icon:typeof Blocks;title:string;description:string;children:React.ReactNode}){return <section aria-labelledby={id} className="grid gap-4"><div><h2 id={id} className="flex items-center gap-2 text-xl font-bold"><Icon className="size-5 text-primary"/>{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{children}</section>}
function ModuleAction({slug,identifier,status}:{slug:string;identifier:string;status:string|undefined}){const action=!status?"install":status==="active"?"deactivate":"activate";return <HubActionForm action={manageHubModuleAction.bind(null,slug)} label={action==="install"?"Installer":action==="activate"?"Activer":"Désactiver"} variant={action==="activate"?"glass":"outline"}><input type="hidden" name="identifier" value={identifier}/><input type="hidden" name="action" value={action}/></HubActionForm>}
function AgentAction({slug,identifier,status}:{slug:string;identifier:string;status:string|undefined}){const action=!status?"install":status==="active"?"disable":"enable";return <HubActionForm action={manageHubAgentAction.bind(null,slug)} label={action==="install"?"Installer":action==="enable"?"Activer":"Désactiver"} variant={action==="enable"?"glass":"outline"}><input type="hidden" name="identifier" value={identifier}/><input type="hidden" name="action" value={action}/></HubActionForm>}
function IntegrationAction({slug,identifier,status}:{slug:string;identifier:string;status:string|undefined}){const action=status==="configured"?"disable":"configure";return <HubActionForm action={manageHubIntegrationAction.bind(null,slug)} label={action==="configure"?"Marquer comme configurée":"Désactiver"}><input type="hidden" name="identifier" value={identifier}/><input type="hidden" name="action" value={action}/></HubActionForm>}
