import Link from "next/link";
import { ChevronLeft, ChevronRight, FilePlus2, FolderOpen } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input, Select } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatOrganizationDate } from "@/config/i18n";
import { serviceRequestMessages as messages } from "@/features/service-requests/messages";
import { serviceRequestListSchema } from "@/features/service-requests/schemas";
import { listOrganizationMembers } from "@/server/organizations/service";
import { listServiceRequestsForOrganization } from "@/server/service-requests/service";

function one(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value;}
function statusVariant(status:string){return status==="closed"?"neutral":status==="incomplete"||status==="needs_review"?"warning":"success";}

export default async function ServiceRequestsPage({params,searchParams}:{params:Promise<{organizationSlug:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const [{organizationSlug},raw]=await Promise.all([params,searchParams]);const filters=serviceRequestListSchema.parse({q:one(raw.q),status:one(raw.status),assignee:one(raw.assignee),country:one(raw.country),archive:one(raw.archive),sort:one(raw.sort),page:one(raw.page)});const result=await listServiceRequestsForOrganization(organizationSlug,filters);const members=await listOrganizationMembers(result.context.organization.id);const pages=Math.max(1,Math.ceil(result.total/result.pageSize));
  const pageHref=(page:number)=>{const query=new URLSearchParams();if(filters.q)query.set("q",filters.q);if(filters.status)query.set("status",filters.status);if(filters.assignee)query.set("assignee",filters.assignee);if(filters.country)query.set("country",filters.country);if(filters.archive!=="active")query.set("archive",filters.archive);if(filters.sort!=="updated_desc")query.set("sort",filters.sort);query.set("page",String(page));return `/app/${organizationSlug}/dossiers?${query}`;};
  return <main className="mx-auto grid w-full max-w-[var(--content-max)] gap-6 p-4 sm:p-8"><PageHeader title="Dossiers" description={`${result.total} demande${result.total>1?"s":""} de service dans cette vue.`} actions={<Button asChild variant="glass"><Link href={`/app/${organizationSlug}/dossiers/nouveau`}><FilePlus2/>Nouveau Dossier</Link></Button>}/>
    <Card className="hover:translate-y-0"><CardContent className="pt-5 sm:pt-6"><form className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><Input name="q" aria-label="Rechercher" placeholder="Référence, titre, service, ville…" defaultValue={filters.q}/><Select name="status" aria-label="Statut" defaultValue={filters.status??""}><option value="">Tous les statuts</option>{Object.entries(messages.statuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select><Select name="assignee" aria-label="Responsable" defaultValue={filters.assignee??""}><option value="">Tous les responsables</option>{members.filter(m=>m.status==="active").map(m=><option key={m.user_id} value={m.user_id}>{[m.first_name,m.last_name].filter(Boolean).join(" ")||"Membre Qualifyr"}</option>)}</Select><Input name="country" aria-label="Code pays" placeholder="Pays (FR, PL…)" maxLength={2} defaultValue={filters.country}/><Select name="archive" aria-label="Archives" defaultValue={filters.archive}><option value="active">Dossiers actifs</option><option value="archived">Archives</option><option value="all">Tous</option></Select><Select name="sort" aria-label="Tri" defaultValue={filters.sort}><option value="updated_desc">Modifiés récemment</option><option value="updated_asc">Modifiés anciennement</option><option value="created_desc">Créés récemment</option><option value="created_asc">Créés anciennement</option></Select><Button type="submit" variant="outline">Appliquer</Button></form></CardContent></Card>
    {!result.items.length?<EmptyState icon={FolderOpen} title={messages.empty} description="Créez une demande manuelle ou ajustez les filtres." action={<Button asChild><Link href={`/app/${organizationSlug}/dossiers/nouveau`}>Créer un Dossier</Link></Button>}/>:<><div className="hidden md:block"><Table><TableHeader><TableRow><TableHead>Référence</TableHead><TableHead>Dossier</TableHead><TableHead>Lieu</TableHead><TableHead>Statut</TableHead><TableHead>Responsable</TableHead><TableHead>Mise à jour</TableHead></TableRow></TableHeader><TableBody>{result.items.map(item=><TableRow key={item.referenceCode}><TableCell><Link className="focus-ring rounded font-mono font-bold text-primary hover:underline" href={`/app/${organizationSlug}/dossiers/${item.referenceCode}`}>{item.referenceCode}</Link></TableCell><TableCell><p className="font-semibold">{item.title}</p><p className="text-xs text-muted-foreground">{item.serviceLabel}{item.requesterName?` · ${item.requesterName}`:""}</p></TableCell><TableCell>{item.city} · {item.countryCode}</TableCell><TableCell><Badge variant={statusVariant(item.status)}>{messages.statuses[item.status]}</Badge>{item.archived?<Badge className="ml-1">Archivé</Badge>:null}</TableCell><TableCell>{item.assigneeName??"Non attribué"}</TableCell><TableCell>{formatOrganizationDate(item.updatedAt,result.context.organization.locale,result.context.organization.timezone)}</TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-3 md:hidden">{result.items.map(item=><Card key={item.referenceCode} className="hover:translate-y-0"><CardContent className="grid gap-3 pt-5"><div className="flex items-center justify-between gap-2"><Link className="font-mono font-bold text-primary" href={`/app/${organizationSlug}/dossiers/${item.referenceCode}`}>{item.referenceCode}</Link><Badge variant={statusVariant(item.status)}>{messages.statuses[item.status]}</Badge></div><div><p className="font-semibold">{item.title}</p><p className="text-sm text-muted-foreground">{item.serviceLabel} · {item.city}</p></div><p className="text-xs text-muted-foreground">Mis à jour {formatOrganizationDate(item.updatedAt,result.context.organization.locale,result.context.organization.timezone)}</p></CardContent></Card>)}</div></>}
    {pages>1?<nav aria-label="Pagination des Dossiers" className="flex items-center justify-center gap-3">{filters.page<=1?<Button variant="outline" disabled><ChevronLeft/>Précédent</Button>:<Button asChild variant="outline"><Link href={pageHref(filters.page-1)}><ChevronLeft/>Précédent</Link></Button>}<span className="text-sm text-muted-foreground">Page {Math.min(filters.page,pages)} sur {pages}</span>{filters.page>=pages?<Button variant="outline" disabled>Suivant<ChevronRight/></Button>:<Button asChild variant="outline"><Link href={pageHref(filters.page+1)}>Suivant<ChevronRight/></Link></Button>}</nav>:null}
  </main>;
}
