import {MapPin,Plus,Settings2} from "lucide-react";
import {Badge} from "@/components/ui/badge";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Field,Input,Select,Textarea} from "@/components/ui/input";
import {PageHeader} from "@/components/ui/page-header";
import {PlaybookActionForm} from "@/features/playbooks/components/action-form";
import {canManagePlaybooks} from "@/features/playbooks/permissions";
import {addCoverageAction,createServiceAction} from "@/server/actions/playbooks";
import {listServices} from "@/server/playbooks/service";

export default async function ServicesPage({params}:{params:Promise<{organizationSlug:string}>}){const {organizationSlug}=await params;const {context,services,coverage}=await listServices(organizationSlug);const canManage=canManagePlaybooks(context.role);return <main className="mx-auto grid w-full max-w-[var(--content-max)] gap-6 p-4 sm:p-8"><PageHeader title="Services" description="Catalogue interne des services proposés et zones couvertes. Aucune cartographie ni géocodage."/>
  {canManage?<div className="grid gap-6 lg:grid-cols-2"><Card className="hover:translate-y-0"><CardHeader><Plus className="size-5 text-primary"/><CardTitle>Créer un Service</CardTitle><CardDescription>Chaque Service appartient uniquement à {context.organization.name}.</CardDescription></CardHeader><CardContent><PlaybookActionForm action={createServiceAction.bind(null,organizationSlug)} label="Créer le Service"><input type="hidden" name="requestId" value={crypto.randomUUID()}/><Field label="Nom"><Input name="name" required maxLength={120} placeholder="Rénovation salle de bain"/></Field><Field label="Description"><Textarea name="description" maxLength={1000}/></Field></PlaybookActionForm></CardContent></Card>
  <Card className="hover:translate-y-0"><CardHeader><MapPin className="size-5 text-primary"/><CardTitle>Ajouter une zone</CardTitle><CardDescription>Pays, ville ou code postal uniquement.</CardDescription></CardHeader><CardContent>{services.length?<PlaybookActionForm action={addCoverageAction.bind(null,organizationSlug)} label="Ajouter la zone" variant="outline"><Field label="Service"><Select name="serviceId">{services.map(service=><option key={service.id} value={service.id}>{service.name}</option>)}</Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Type"><Select name="areaType"><option value="country">Pays</option><option value="city">Ville</option><option value="postal_code">Code postal</option></Select></Field><Field label="Code pays"><Input name="countryCode" required maxLength={2} defaultValue="BE"/></Field></div><Field label="Valeur"><Input name="value" required maxLength={120} placeholder="Namur"/></Field></PlaybookActionForm>:<p className="text-sm text-muted-foreground">Créez d’abord un Service.</p>}</CardContent></Card></div>:null}
  <section aria-labelledby="services-list" className="grid gap-4"><h2 id="services-list" className="text-xl font-bold">Services configurés</h2>{services.length?<div className="grid gap-4 md:grid-cols-2">{services.map(service=><Card key={service.id} className="hover:translate-y-0"><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle>{service.name}</CardTitle><Badge variant={service.status==="active"?"success":"neutral"}>{service.status}</Badge></div><CardDescription>{service.description??"Sans description"}</CardDescription></CardHeader><CardContent><p className="mb-2 flex items-center gap-2 text-sm font-semibold"><Settings2 className="size-4"/>Zones couvertes</p><ul className="flex flex-wrap gap-2">{coverage.filter(area=>area.service_definition_id===service.id).map(area=><li key={area.id}><Badge>{area.area_type} · {area.country_code} · {area.value}</Badge></li>)}{coverage.every(area=>area.service_definition_id!==service.id)?<li className="text-sm text-muted-foreground">Aucune zone : la règle de couverture échouera.</li>:null}</ul></CardContent></Card>)}</div>:<p className="text-sm text-muted-foreground">Aucun Service.</p>}</section></main>;}
