import Link from "next/link";
import {BookOpen,FlaskConical,Plus} from "lucide-react";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Field,Input,Select,Textarea} from "@/components/ui/input";
import {PageHeader} from "@/components/ui/page-header";
import {PlaybookActionForm} from "@/features/playbooks/components/action-form";
import {playbookMessages} from "@/features/playbooks/messages";
import {canManagePlaybooks} from "@/features/playbooks/permissions";
import {createPlaybookAction,installDemoPlaybookAction} from "@/server/actions/playbooks";
import {listPlaybooks} from "@/server/playbooks/service";

export default async function PlaybooksPage({params}:{params:Promise<{organizationSlug:string}>}){const {organizationSlug}=await params;const {context,playbooks,versions,services}=await listPlaybooks(organizationSlug);const canManage=canManagePlaybooks(context.role);return <main className="mx-auto grid w-full max-w-[var(--content-max)] gap-6 p-4 sm:p-8"><PageHeader title="Playbooks" description="Schémas de qualification déterministes, versionnés et explicables." actions={<Button asChild variant="outline"><Link href={`/app/${organizationSlug}/services`}>Gérer les Services</Link></Button>}/>
  {canManage&&services.length?<div className="grid gap-6 xl:grid-cols-2"><Card className="hover:translate-y-0"><CardHeader><Plus className="size-5 text-primary"/><CardTitle>Créer un Playbook</CardTitle><CardDescription>Le premier brouillon reprend le schéma de rénovation, entièrement modifiable avant publication.</CardDescription></CardHeader><CardContent><PlaybookActionForm action={createPlaybookAction.bind(null,organizationSlug)} label="Créer le Playbook"><input type="hidden" name="requestId" value={crypto.randomUUID()}/><Field label="Service"><Select name="serviceId">{services.filter(service=>service.status==="active").map(service=><option key={service.id} value={service.id}>{service.name}</option>)}</Select></Field><Field label="Nom"><Input name="name" required maxLength={160}/></Field><Field label="Description"><Textarea name="description" maxLength={1000}/></Field></PlaybookActionForm></CardContent></Card>
  <Card className="border-primary/20 bg-primary/[0.03] hover:translate-y-0"><CardHeader><FlaskConical className="size-5 text-primary"/><CardTitle>Scénario de démonstration</CardTitle><CardDescription>Installe « Demande de devis rénovation », ajoute Namur comme zone et publie la version 1.</CardDescription></CardHeader><CardContent><PlaybookActionForm action={installDemoPlaybookAction.bind(null,organizationSlug,services[0]!.id)} label="Installer et publier la démonstration" variant="outline"><input type="hidden" name="requestId" value={crypto.randomUUID()}/><p className="text-sm text-muted-foreground">Service utilisé : {services[0]!.name}. Pour le scénario demandé, nommez-le « Rénovation salle de bain ».</p></PlaybookActionForm></CardContent></Card></div>:null}
  {!services.length?<Card className="hover:translate-y-0"><CardContent className="pt-6"><p className="text-sm text-muted-foreground">Créez un Service avant de créer un Playbook.</p><Button asChild className="mt-4"><Link href={`/app/${organizationSlug}/services`}>Créer un Service</Link></Button></CardContent></Card>:null}
  <section aria-labelledby="playbooks-list" className="grid gap-4"><h2 id="playbooks-list" className="text-xl font-bold">Playbooks configurés</h2>{playbooks.length?<div className="grid gap-4 md:grid-cols-2">{playbooks.map(playbook=>{const active=versions.find(version=>version.id===playbook.active_version_id);return <Card key={playbook.id} className="hover:translate-y-0"><CardHeader><BookOpen className="size-5 text-primary"/><div className="flex items-center justify-between gap-2"><CardTitle>{playbook.name}</CardTitle><Badge variant={playbook.status==="active"?"success":"neutral"}>{playbookMessages.statuses[playbook.status]}</Badge></div><CardDescription>{playbook.description??"Sans description"}</CardDescription></CardHeader><CardContent className="flex items-center justify-between gap-3"><span className="text-sm text-muted-foreground">{active?`Version active v${active.version_number}`:"Aucune version publiée"}</span><Button asChild variant="outline"><Link href={`/app/${organizationSlug}/playbooks/${playbook.id}`}>Ouvrir</Link></Button></CardContent></Card>;})}</div>:<p className="text-sm text-muted-foreground">Aucun Playbook.</p>}</section></main>;}
