"use server";
import {revalidatePath} from "next/cache";
import {z} from "zod";
import {intakeMessageSchema,factResolutionSchema} from "@/features/ai-intake/schemas";
import type {IntakeActionState} from "@/features/ai-intake/state";
import {parseHumanCorrection} from "@/features/ai-intake/fact-merge";
import {chooseNextQuestion} from "@/features/ai-intake/next-question";
import type {Json} from "@/types/database.generated";
import {createClient} from "@/lib/supabase/server";
import {getAiIntake,currentConfirmedValues} from "@/server/ai-intake/service";
import {extractIntake} from "@/server/ai-intake/orchestrator";
import {AiNotConfiguredError} from "@/services/ai";

const refresh=(slug:string,reference:string)=>{revalidatePath(`/app/${slug}/dossiers/${reference}`);revalidatePath(`/app/${slug}/dossiers/${reference}/ai-intake`);revalidatePath(`/app/${slug}/dossiers/${reference}/qualification`);};
const fail=(message:string):IntakeActionState=>({status:"error",message});

export async function startAiIntakeAction(slug:string,reference:string,state:IntakeActionState,formData:FormData):Promise<IntakeActionState>{void state;void formData;const bundle=await getAiIntake(slug,reference);if(!bundle.schema)return fail("Associez d’abord un Playbook publié.");const locale=bundle.detail.requesterLocale??bundle.context.organization.locale??"fr-FR";const supabase=await createClient();const {error}=await supabase.rpc("start_intake_session",{target_organization_id:bundle.context.organization.id,target_reference:reference,requested_locale:locale});if(error)return fail("Impossible de démarrer l’assistant.");refresh(slug,reference);return {status:"success",message:"Session démarrée."};}

export async function sendAiIntakeMessageAction(slug:string,reference:string,state:IntakeActionState,formData:FormData):Promise<IntakeActionState>{void state;const bundle=await getAiIntake(slug,reference);if(!bundle.schema||!bundle.session)return fail("Démarrez d’abord une session.");const parsed=intakeMessageSchema.safeParse({message:formData.get("message"),requestId:formData.get("requestId")});if(!parsed.success)return fail("Le message doit contenir entre 1 et 5 000 caractères.");const supabase=await createClient();const {data:messageId,error:messageError}=await supabase.rpc("append_intake_user_message",{target_organization_id:bundle.context.organization.id,target_session_id:bundle.session.id,requested_content:parsed.data.message,requested_request_id:parsed.data.requestId});if(messageError||!messageId)return fail("Le message n’a pas pu être enregistré.");const correlationId=crypto.randomUUID();const started=Date.now();
  try{const knownValues=bundle.result?.field_values&&typeof bundle.result.field_values==="object"&&!Array.isArray(bundle.result.field_values)?bundle.result.field_values:{};const extraction=await extractIntake({organizationId:bundle.context.organization.id,correlationId,locale:bundle.session.locale,message:parsed.data.message,services:bundle.services,schema:bundle.schema,knownValues,facts:bundle.facts.map(f=>({field_key:f.field_key,value:f.value as string|number|boolean,status:f.status,confidence:Number(f.confidence)})),recentMessages:bundle.messages.slice(-6).map(m=>({role:m.role,content:m.content}))});const {error}=await supabase.rpc("record_intake_success",{target_organization_id:bundle.context.organization.id,target_session_id:bundle.session.id,target_message_id:messageId,requested_output:extraction.output as unknown as Json,requested_provider:extraction.provider,requested_model:extraction.model,requested_instructions_version:extraction.instructionsVersion,requested_latency_ms:extraction.latencyMs,requested_input_tokens:extraction.usage?.inputTokens??0,requested_output_tokens:extraction.usage?.outputTokens??0,requested_correlation_id:correlationId});if(error)throw new Error("persistence_failed");
  }catch(error){const timedOut=error instanceof Error&&(error.name==="TimeoutError"||error.message.toLowerCase().includes("timeout"));const invalid=error instanceof z.ZodError||error instanceof Error&&error.message==="invalid_output";await supabase.rpc("record_intake_failure",{target_organization_id:bundle.context.organization.id,target_session_id:bundle.session.id,target_message_id:messageId,requested_provider:error instanceof AiNotConfiguredError?"disabled":"configured",requested_model:"unavailable",requested_instructions_version:"intake-v1",requested_status:timedOut?"timed_out":invalid?"invalid_output":"failed",requested_error_code:error instanceof AiNotConfiguredError?"provider_not_configured":timedOut?"provider_timeout":invalid?"invalid_structured_output":"provider_unavailable",requested_latency_ms:Date.now()-started,requested_correlation_id:correlationId});refresh(slug,reference);return fail(error instanceof AiNotConfiguredError?"Aucun fournisseur IA n’est configuré. Le message est conservé et la saisie manuelle reste disponible.":"L’extraction est momentanément indisponible. Le message et le Dossier sont conservés.");}
  await recalculateFromConfirmedFacts(bundle.context.organization.id,reference,bundle.facts,bundle.result?.field_values,bundle.result?.evidence_values);refresh(slug,reference);return {status:"success",message:"Demande analysée et qualification recalculée."};}

export async function resolveAiIntakeFactAction(slug:string,reference:string,state:IntakeActionState,formData:FormData):Promise<IntakeActionState>{void state;const bundle=await getAiIntake(slug,reference);if(!bundle.session)return fail("Session introuvable.");const parsed=factResolutionSchema.safeParse({factId:formData.get("factId"),action:formData.get("action"),value:formData.get("value")||undefined});if(!parsed.success)return fail("Action invalide.");const fact=bundle.facts.find(item=>item.id===parsed.data.factId);if(!fact)return fail("Fait introuvable.");let value=fact.value as string|number|boolean;if(parsed.data.action==="correct"){if(!parsed.data.value)return fail("Saisissez la valeur corrigée.");try{value=parseHumanCorrection(parsed.data.value,fact.value_type);}catch{return fail("La correction ne correspond pas au type attendu.");}}
  const supabase=await createClient();const {error}=await supabase.rpc("resolve_extracted_fact",{target_organization_id:bundle.context.organization.id,target_fact_id:fact.id,requested_action:parsed.data.action,requested_value:value as Json});if(error)return fail("Le fait n’a pas pu être mis à jour.");const {data:facts}=await supabase.from("extracted_facts").select("field_key,value,status,confidence").eq("organization_id",bundle.context.organization.id).eq("intake_session_id",bundle.session.id);await recalculateFromConfirmedFacts(bundle.context.organization.id,reference,facts??[],bundle.result?.field_values,bundle.result?.evidence_values);const question=chooseNextQuestion({playbook:bundle.schema,facts:(facts??[]).map(item=>({fieldKey:item.field_key,value:item.value as string|number|boolean,status:item.status,confidence:Number(item.confidence)})),serviceUncertain:bundle.session.detected_service_definition_id===null||Number(bundle.session.service_confidence)<.7});await supabase.rpc("update_intake_next_question",{target_organization_id:bundle.context.organization.id,target_session_id:bundle.session.id,requested_question:question});refresh(slug,reference);return {status:"success",message:"Fait mis à jour et qualification recalculée."};}

async function recalculateFromConfirmedFacts(organizationId:string,reference:string,facts:Array<{field_key:string;value:unknown;status:string}>,existingValues:Json|undefined,existingEvidence:Json|undefined){const base=existingValues&&typeof existingValues==="object"&&!Array.isArray(existingValues)?existingValues:{};const values={...base,...currentConfirmedValues(facts)};const evidence=existingEvidence&&typeof existingEvidence==="object"&&!Array.isArray(existingEvidence)?existingEvidence:{};const supabase=await createClient();await supabase.rpc("calculate_dossier_qualification",{target_organization_id:organizationId,target_reference:reference,requested_values:values as Json,requested_evidence:evidence as Json});}
