"use server";
import {revalidatePath} from "next/cache";
import {hubActionSchema,hubPackSchema,parseHubConfiguration} from "@/features/hub/schemas";
import type {HubActionState} from "@/features/hub/types";
import {getHub} from "@/server/hub/service";
import {createClient} from "@/lib/supabase/server";
import type {Json} from "@/types/database.generated";
const fail=(message:string):HubActionState=>({status:"error",message});const refresh=(slug:string)=>revalidatePath(`/app/${slug}/hub`);const configurationJson=(value:string|undefined)=>parseHubConfiguration(value) as Json;
export async function manageHubModuleAction(slug:string,state:HubActionState,formData:FormData):Promise<HubActionState>{void state;const parsed=hubActionSchema.safeParse({identifier:formData.get("identifier"),action:formData.get("action"),configuration:formData.get("configuration")||undefined});if(!parsed.success||!["install","activate","deactivate","remove","configure"].includes(parsed.data.action))return fail("Action de module invalide.");try{const hub=await getHub(slug);const supabase=await createClient();const {error}=await supabase.rpc("manage_hub_module",{target_organization_id:hub.context.id,requested_identifier:parsed.data.identifier,requested_action:parsed.data.action,requested_configuration:configurationJson(parsed.data.configuration)});if(error)return fail("Le module n’a pas pu être mis à jour.");refresh(slug);return {status:"success",message:"Module mis à jour."};}catch{return fail("La configuration doit être un objet JSON sans secret.");}}
export async function applyHubPackAction(slug:string,state:HubActionState,formData:FormData):Promise<HubActionState>{void state;const parsed=hubPackSchema.safeParse({code:formData.get("code")});if(!parsed.success)return fail("Pack invalide.");const hub=await getHub(slug);const supabase=await createClient();const {error}=await supabase.rpc("apply_hub_pack",{target_organization_id:hub.context.id,requested_pack_code:parsed.data.code});if(error)return fail("Le pack n’a pas pu être appliqué.");refresh(slug);return {status:"success",message:"Pack appliqué sans supprimer de données."};}
export async function manageHubAgentAction(slug:string,state:HubActionState,formData:FormData):Promise<HubActionState>{void state;const parsed=hubActionSchema.safeParse({identifier:formData.get("identifier"),action:formData.get("action"),configuration:formData.get("configuration")||undefined});if(!parsed.success||!["install","enable","disable","configure"].includes(parsed.data.action))return fail("Action d’agent invalide.");try{const hub=await getHub(slug);const supabase=await createClient();const {error}=await supabase.rpc("manage_hub_agent",{target_organization_id:hub.context.id,requested_identifier:parsed.data.identifier,requested_action:parsed.data.action,requested_configuration:configurationJson(parsed.data.configuration)});if(error)return fail("L’agent n’a pas pu être mis à jour.");refresh(slug);return {status:"success",message:"Registre d’agent mis à jour."};}catch{return fail("La configuration doit être un objet JSON sans secret.");}}
export async function manageHubIntegrationAction(slug:string,state:HubActionState,formData:FormData):Promise<HubActionState>{void state;const parsed=hubActionSchema.safeParse({identifier:formData.get("identifier"),action:formData.get("action"),configuration:formData.get("configuration")||undefined});if(!parsed.success||!["configure","disable"].includes(parsed.data.action))return fail("Action d’intégration invalide.");try{const hub=await getHub(slug);const supabase=await createClient();const {error}=await supabase.rpc("manage_hub_integration",{target_organization_id:hub.context.id,requested_identifier:parsed.data.identifier,requested_action:parsed.data.action,requested_configuration:configurationJson(parsed.data.configuration)});if(error)return fail("L’intégration n’a pas pu être mise à jour.");refresh(slug);return {status:"success",message:"Intégration enregistrée sans secret ni connexion externe."};}catch{return fail("La configuration doit être un objet JSON sans secret.");}}
