"use server";

import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {renovationDemoSchema} from "@/features/playbooks/demo";
import {canManagePlaybooks,canValidateQualification} from "@/features/playbooks/permissions";
import {associatePlaybookSchema,coverageAreaSchema,createPlaybookSchema,createServiceSchema,editorSchema,parseEditorSchema,versionIdSchema} from "@/features/playbooks/schemas";
import type {PlaybookActionState} from "@/features/playbooks/state";
import type {Json} from "@/types/database.generated";
import {createClient} from "@/lib/supabase/server";
import {getDossierQualification} from "@/server/playbooks/service";
import {requireServiceRequestContext} from "@/server/service-requests/service";

const values=(formData:FormData,keys:string[])=>Object.fromEntries(keys.map(key=>[key,formData.get(key)]));
const fail=(message="Action impossible. Vérifiez les informations et réessayez."):PlaybookActionState=>({status:"error",message});
const refresh=(slug:string)=>{revalidatePath(`/app/${slug}`);revalidatePath(`/app/${slug}/services`);revalidatePath(`/app/${slug}/playbooks`);revalidatePath(`/app/${slug}/dossiers`);};
export async function createServiceAction(slug:string,_state:PlaybookActionState,formData:FormData):Promise<PlaybookActionState>{const context=await requireServiceRequestContext(slug);if(!canManagePlaybooks(context.role))return fail();const parsed=createServiceSchema.safeParse(values(formData,["name","description","requestId"]));if(!parsed.success)return {status:"error",message:"Service invalide.",fieldErrors:parsed.error.flatten().fieldErrors};const supabase=await createClient();const {error}=await supabase.rpc("create_service_definition",{target_organization_id:context.organization.id,requested_name:parsed.data.name,requested_description:parsed.data.description??"",request_id:parsed.data.requestId});if(error)return fail();refresh(slug);return {status:"success",message:"Service créé."};}
export async function addCoverageAction(slug:string,_state:PlaybookActionState,formData:FormData):Promise<PlaybookActionState>{const context=await requireServiceRequestContext(slug);if(!canManagePlaybooks(context.role))return fail();const parsed=coverageAreaSchema.safeParse(values(formData,["serviceId","areaType","countryCode","value"]));if(!parsed.success)return fail("Zone invalide.");const supabase=await createClient();const {error}=await supabase.rpc("add_coverage_area",{target_organization_id:context.organization.id,target_service_id:parsed.data.serviceId,requested_type:parsed.data.areaType,requested_country_code:parsed.data.countryCode,requested_value:parsed.data.value});if(error)return fail();refresh(slug);return {status:"success",message:"Zone ajoutée."};}
export async function createPlaybookAction(slug:string,_state:PlaybookActionState,formData:FormData):Promise<PlaybookActionState>{const context=await requireServiceRequestContext(slug);if(!canManagePlaybooks(context.role))return fail();const parsed=createPlaybookSchema.safeParse(values(formData,["serviceId","name","description","requestId"]));if(!parsed.success)return fail("Playbook invalide.");const supabase=await createClient();const {data,error}=await supabase.rpc("create_playbook",{target_organization_id:context.organization.id,target_service_id:parsed.data.serviceId,requested_name:parsed.data.name,requested_description:parsed.data.description??"",requested_schema:renovationDemoSchema as unknown as Json,request_id:parsed.data.requestId});if(error||!data?.[0])return fail();refresh(slug);redirect(`/app/${slug}/playbooks/${data[0].playbook_id}`);}
export async function installDemoPlaybookAction(slug:string,serviceId:string,_state:PlaybookActionState,formData:FormData):Promise<PlaybookActionState>{const context=await requireServiceRequestContext(slug);if(!canManagePlaybooks(context.role))return fail();const requestId=String(formData.get("requestId")??"");if(!/^[0-9a-f-]{36}$/i.test(requestId))return fail();const supabase=await createClient();await supabase.rpc("add_coverage_area",{target_organization_id:context.organization.id,target_service_id:serviceId,requested_type:"city",requested_country_code:"BE",requested_value:"Namur"});const {data,error}=await supabase.rpc("create_playbook",{target_organization_id:context.organization.id,target_service_id:serviceId,requested_name:"Demande de devis rénovation",requested_description:"Qualification déterministe d’un projet de rénovation de salle de bain.",requested_schema:renovationDemoSchema as unknown as Json,request_id:requestId});if(error||!data?.[0])return fail();const {error:publishError}=await supabase.rpc("publish_playbook_version",{target_organization_id:context.organization.id,target_version_id:data[0].version_id});if(publishError)return fail();refresh(slug);redirect(`/app/${slug}/playbooks/${data[0].playbook_id}`);}
export async function updatePlaybookDraftAction(slug:string,playbookId:string,_state:PlaybookActionState,formData:FormData):Promise<PlaybookActionState>{const context=await requireServiceRequestContext(slug);if(!canManagePlaybooks(context.role))return fail();const parsed=editorSchema.safeParse(values(formData,["versionId","lockVersion","fields","proofs","nextAction"]));if(!parsed.success)return fail("Éditeur invalide.");const definition=parseEditorSchema(parsed.data.fields,parsed.data.proofs,parsed.data.nextAction);if(!definition.success)return fail("Le schéma contient une ligne invalide ou une clé dupliquée.");const supabase=await createClient();const {error}=await supabase.rpc("update_playbook_draft",{target_organization_id:context.organization.id,target_version_id:parsed.data.versionId,expected_version:parsed.data.lockVersion,requested_schema:definition.data as unknown as Json});if(error)return fail(error.message.includes("version_conflict")?"Cette version a été modifiée. Rechargez la page.":undefined);refresh(slug);revalidatePath(`/app/${slug}/playbooks/${playbookId}`);return {status:"success",message:"Brouillon enregistré."};}
export async function publishPlaybookAction(slug:string,playbookId:string,_state:PlaybookActionState,formData:FormData):Promise<PlaybookActionState>{const context=await requireServiceRequestContext(slug);if(!canManagePlaybooks(context.role))return fail();const parsed=versionIdSchema.safeParse(values(formData,["versionId"]));if(!parsed.success)return fail();const supabase=await createClient();const {error}=await supabase.rpc("publish_playbook_version",{target_organization_id:context.organization.id,target_version_id:parsed.data.versionId});if(error)return fail();refresh(slug);revalidatePath(`/app/${slug}/playbooks/${playbookId}`);return {status:"success",message:"Version publiée et désormais immuable."};}
export async function createPlaybookVersionAction(slug:string,playbookId:string,state:PlaybookActionState,formData:FormData):Promise<PlaybookActionState>{void state;void formData;const context=await requireServiceRequestContext(slug);if(!canManagePlaybooks(context.role))return fail();const supabase=await createClient();const {error}=await supabase.rpc("create_playbook_version",{target_organization_id:context.organization.id,target_playbook_id:playbookId});if(error)return fail(error.message.includes("draft_exists")?"Un brouillon existe déjà.":undefined);refresh(slug);revalidatePath(`/app/${slug}/playbooks/${playbookId}`);return {status:"success",message:"Nouvelle version brouillon créée."};}
export async function associateDossierPlaybookAction(slug:string,reference:string,_state:PlaybookActionState,formData:FormData):Promise<PlaybookActionState>{const context=await requireServiceRequestContext(slug);const parsed=associatePlaybookSchema.safeParse(values(formData,["versionId"]));if(!parsed.success)return fail();const supabase=await createClient();const {error}=await supabase.rpc("associate_dossier_playbook",{target_organization_id:context.organization.id,target_reference:reference,target_version_id:parsed.data.versionId});if(error)return fail();refresh(slug);revalidatePath(`/app/${slug}/dossiers/${reference}`);revalidatePath(`/app/${slug}/dossiers/${reference}/qualification`);return {status:"success",message:"Playbook associé."};}
export async function calculateQualificationAction(slug:string,reference:string,_state:PlaybookActionState,formData:FormData):Promise<PlaybookActionState>{const bundle=await getDossierQualification(slug,reference);if(!bundle.schema)return fail();const input:Record<string,unknown>={};for(const field of bundle.schema.fields){const raw=formData.get(`value:${field.key}`);if(typeof raw!=="string")continue;if(field.type==="number")input[field.key]=raw===""?null:Number(raw);else input[field.key]=raw.trim();}const evidence:Record<string,unknown[]>={};for(const proof of bundle.schema.proofs){const count=Math.max(0,Math.min(proof.minimum,Number(formData.get(`proof:${proof.key}`)??0)));evidence[proof.key]=Array.from({length:Number.isFinite(count)?count:0},(_,index)=>({reference:`declared-${index+1}`}));}const supabase=await createClient();const {error}=await supabase.rpc("calculate_dossier_qualification",{target_organization_id:bundle.context.organization.id,target_reference:reference,requested_values:input as Json,requested_evidence:evidence as Json});if(error)return fail();refresh(slug);revalidatePath(`/app/${slug}/dossiers/${reference}`);revalidatePath(`/app/${slug}/dossiers/${reference}/qualification`);return {status:"success",message:"Qualification recalculée."};}
export async function validateQualificationAction(slug:string,reference:string,state:PlaybookActionState,formData:FormData):Promise<PlaybookActionState>{void state;void formData;const context=await requireServiceRequestContext(slug);if(!canValidateQualification(context.role))return fail();const supabase=await createClient();const {error}=await supabase.rpc("validate_dossier_qualification",{target_organization_id:context.organization.id,target_reference:reference});if(error)return fail("La qualification doit être complète avant validation.");refresh(slug);revalidatePath(`/app/${slug}/dossiers/${reference}`);revalidatePath(`/app/${slug}/dossiers/${reference}/qualification`);return {status:"success",message:"Qualification validée. Le Dossier est qualifié."};}
