"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { assignServiceRequestSchema, createServiceRequestSchema, deleteServiceRequestSchema, transitionServiceRequestSchema, updateServiceRequestSchema, versionedActionSchema } from "@/features/service-requests/schemas";
import { serviceRequestMessages } from "@/features/service-requests/messages";
import type { ServiceRequestActionState } from "@/features/service-requests/types";
import { createClient } from "@/lib/supabase/server";
import { requireServiceRequestContext } from "@/server/service-requests/service";

const formValues=(formData:FormData,keys:readonly string[])=>Object.fromEntries(keys.map(key=>[key,formData.get(key)]));
const formKeys=["title","serviceLabel","originalRequest","requesterFirstName","requesterLastName","requesterEmail","requesterPhone","preferredContactChannel","requesterLocale","countryCode","postalCode","city","addressLine1"] as const;
const dbNullable=<T,>(value:T|undefined)=>value??null as T;
function errorState(error?:{message?:string}):ServiceRequestActionState{return {status:"error",message:error?.message?.includes("version_conflict")?serviceRequestMessages.conflict:serviceRequestMessages.genericError};}
function revalidate(slug:string,reference?:string){revalidatePath(`/app/${slug}`);revalidatePath(`/app/${slug}/dossiers`);if(reference)revalidatePath(`/app/${slug}/dossiers/${reference}`);}

export async function createServiceRequestAction(organizationSlug:string,_state:ServiceRequestActionState,formData:FormData):Promise<ServiceRequestActionState>{
  const context=await requireServiceRequestContext(organizationSlug);const parsed=createServiceRequestSchema.safeParse(formValues(formData,[...formKeys,"assignedUserId","requestId"]));
  if(!parsed.success)return {status:"error",message:serviceRequestMessages.genericError,fieldErrors:parsed.error.flatten().fieldErrors};
  const supabase=await createClient();const v=parsed.data;const {data,error}=await supabase.rpc("create_service_request",{target_organization_id:context.organization.id,requested_title:v.title,requested_original_request:v.originalRequest,requested_service_label:v.serviceLabel,requested_first_name:v.requesterFirstName??"",requested_last_name:v.requesterLastName??"",requested_email:dbNullable(v.requesterEmail),requested_phone:dbNullable(v.requesterPhone),requested_contact_channel:v.preferredContactChannel,requested_locale:dbNullable(v.requesterLocale),requested_country_code:v.countryCode,requested_postal_code:v.postalCode,requested_city:v.city,requested_address:v.addressLine1??"",requested_assignee:dbNullable(v.assignedUserId),request_id:v.requestId});
  if(error||!data?.[0])return errorState(error??undefined);revalidate(organizationSlug);redirect(`/app/${organizationSlug}/dossiers/${data[0].reference_code}`);
}

export async function updateServiceRequestAction(organizationSlug:string,reference:string,_state:ServiceRequestActionState,formData:FormData):Promise<ServiceRequestActionState>{
  const context=await requireServiceRequestContext(organizationSlug);const parsed=updateServiceRequestSchema.safeParse(formValues(formData,[...formKeys,"lockVersion"]));if(!parsed.success)return {status:"error",message:serviceRequestMessages.genericError,fieldErrors:parsed.error.flatten().fieldErrors};
  const v=parsed.data;const supabase=await createClient();const {error}=await supabase.rpc("update_service_request",{target_organization_id:context.organization.id,target_reference:reference,expected_version:v.lockVersion,requested_title:v.title,requested_original_request:v.originalRequest,requested_service_label:v.serviceLabel,requested_first_name:v.requesterFirstName??"",requested_last_name:v.requesterLastName??"",requested_email:dbNullable(v.requesterEmail),requested_phone:dbNullable(v.requesterPhone),requested_contact_channel:v.preferredContactChannel,requested_locale:dbNullable(v.requesterLocale),requested_country_code:v.countryCode,requested_postal_code:v.postalCode,requested_city:v.city,requested_address:v.addressLine1??""});if(error)return errorState(error);revalidate(organizationSlug,reference);return {status:"success",message:"Le Dossier a été mis à jour."};
}

export async function transitionServiceRequestAction(organizationSlug:string,reference:string,_state:ServiceRequestActionState,formData:FormData):Promise<ServiceRequestActionState>{const context=await requireServiceRequestContext(organizationSlug);const parsed=transitionServiceRequestSchema.safeParse(formValues(formData,["status","reason","lockVersion"]));if(!parsed.success)return errorState();const supabase=await createClient();const {error}=await supabase.rpc("transition_service_request_status",{target_organization_id:context.organization.id,target_reference:reference,expected_version:parsed.data.lockVersion,requested_status:parsed.data.status,reason:dbNullable(parsed.data.reason)});if(error)return errorState(error);revalidate(organizationSlug,reference);return {status:"success",message:"Le statut a été mis à jour."};}
export async function assignServiceRequestAction(organizationSlug:string,reference:string,_state:ServiceRequestActionState,formData:FormData):Promise<ServiceRequestActionState>{const context=await requireServiceRequestContext(organizationSlug);const parsed=assignServiceRequestSchema.safeParse(formValues(formData,["assignedUserId","lockVersion"]));if(!parsed.success)return errorState();const supabase=await createClient();const {error}=await supabase.rpc("assign_service_request",{target_organization_id:context.organization.id,target_reference:reference,expected_version:parsed.data.lockVersion,requested_assignee:dbNullable(parsed.data.assignedUserId)});if(error)return errorState(error);revalidate(organizationSlug,reference);return {status:"success",message:"Le responsable a été mis à jour."};}
export async function archiveServiceRequestAction(organizationSlug:string,reference:string,shouldArchive:boolean,_state:ServiceRequestActionState,formData:FormData):Promise<ServiceRequestActionState>{const context=await requireServiceRequestContext(organizationSlug);const parsed=versionedActionSchema.safeParse(formValues(formData,["lockVersion"]));if(!parsed.success)return errorState();const supabase=await createClient();const {error}=await supabase.rpc("set_service_request_archived",{target_organization_id:context.organization.id,target_reference:reference,expected_version:parsed.data.lockVersion,should_archive:shouldArchive});if(error)return errorState(error);revalidate(organizationSlug,reference);return {status:"success",message:shouldArchive?"Le Dossier a été archivé.":"Le Dossier a été restauré."};}
export async function deleteServiceRequestAction(organizationSlug:string,reference:string,_state:ServiceRequestActionState,formData:FormData):Promise<ServiceRequestActionState>{const context=await requireServiceRequestContext(organizationSlug);const parsed=deleteServiceRequestSchema.safeParse(formValues(formData,["confirmationReference"]));if(!parsed.success)return errorState();const supabase=await createClient();const {error}=await supabase.rpc("delete_service_request",{target_organization_id:context.organization.id,target_reference:reference,confirmation_reference:parsed.data.confirmationReference});if(error)return errorState(error);revalidate(organizationSlug);redirect(`/app/${organizationSlug}/dossiers`);}
