import "server-only";
import {notFound} from "next/navigation";
import {playbookSchema} from "@/features/playbooks/schemas";
import {canUseAiIntake,canViewAiExecutions} from "@/features/ai-intake/permissions";
import {createClient} from "@/lib/supabase/server";
import {getServiceRequestForOrganization} from "@/server/service-requests/service";

export async function getAiIntake(organizationSlug:string,reference:string){
  const dossier=await getServiceRequestForOrganization(organizationSlug,reference);const ownership={createdBy:dossier.detail.createdBy,assignedUserId:dossier.detail.assignedUserId};if(!canUseAiIntake(dossier.context.role,dossier.context.userId,ownership))notFound();if(!dossier.detail.playbookVersionId) return {...dossier,schema:null,services:[],result:null,session:null,messages:[],facts:[],executions:[]};
  const supabase=await createClient();const [{data:version,error:versionError},{data:services,error:serviceError},{data:sessions,error:sessionError},{data:result,error:resultError}]=await Promise.all([supabase.from("playbook_versions").select("id,schema_definition").eq("organization_id",dossier.context.organization.id).eq("id",dossier.detail.playbookVersionId).eq("status","published").maybeSingle(),supabase.from("service_definitions").select("id,code,name").eq("organization_id",dossier.context.organization.id).eq("status","active").order("name"),supabase.from("intake_sessions").select("id,status,locale,next_question,detected_service_definition_id,service_confidence,created_at,updated_at").eq("organization_id",dossier.context.organization.id).eq("service_request_id",dossier.detail.id).eq("status","active").maybeSingle(),supabase.from("qualification_results").select("field_values,evidence_values,missing_information,recommended_status").eq("organization_id",dossier.context.organization.id).eq("service_request_id",dossier.detail.id).maybeSingle()]);if(versionError||serviceError||sessionError||resultError||!version)throw new Error("ai_intake_unavailable");const parsed=playbookSchema.safeParse(version.schema_definition);if(!parsed.success)throw new Error("invalid_playbook_schema");const session=sessions??null;if(!session)return {...dossier,schema:parsed.data,services:services??[],result,session:null,messages:[],facts:[],executions:[]};
  const [{data:messages,error:messageError},{data:facts,error:factError},executionResult]=await Promise.all([supabase.from("intake_messages").select("id,role,content,sequence_number,created_at").eq("organization_id",dossier.context.organization.id).eq("intake_session_id",session.id).order("sequence_number"),supabase.from("extracted_facts").select("id,field_key,value,value_type,source_type,source_message_id,source_excerpt,confidence,status,created_by_type,created_at,updated_at").eq("organization_id",dossier.context.organization.id).eq("intake_session_id",session.id).order("created_at",{ascending:false}),canViewAiExecutions(dossier.context.role)?supabase.from("ai_executions").select("id,provider,model,status,latency_ms,input_tokens,output_tokens,error_code,correlation_id,created_at").eq("organization_id",dossier.context.organization.id).eq("intake_session_id",session.id).order("created_at",{ascending:false}):Promise.resolve({data:[],error:null})]);if(messageError||factError||executionResult.error)throw new Error("ai_intake_unavailable");return {...dossier,schema:parsed.data,services:services??[],result,session,messages:messages??[],facts:facts??[],executions:executionResult.data??[]};
}

export function currentConfirmedValues(facts:Array<{field_key:string;value:unknown;status:string}>){const values:Record<string,unknown>={};for(const fact of [...facts].reverse())if(fact.status==="confirmed")values[fact.field_key]=fact.value;return values;}
