import { CheckCircle2, Copy, LockKeyhole, MailCheck, ShieldCheck } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { emailIntakeMessages as messages } from "@/features/email-intake/messages";
import { configureEmailChannelAction } from "@/server/actions/email-intake";
import { getEmailChannelSettings } from "@/server/email-intake/settings";

export default async function EmailChannelPage({ params }: { params: Promise<{ organizationSlug: string }> }) {
  const { organizationSlug } = await params;
  const { channel, address, providerConfigured, migrationReady } = await getEmailChannelSettings(organizationSlug);
  const active = channel?.status === "active";
  return <main className="mx-auto grid w-full max-w-[var(--content-max)] gap-6 p-4 sm:p-8">
    <div><Badge variant={active ? "success" : "neutral"}>{active ? "Actif" : "Inactif"}</Badge><h1 className="mt-3 text-3xl font-black tracking-[-.04em]">{messages.title}</h1><p className="mt-2 max-w-3xl text-muted-foreground">{messages.description}</p></div>
    {!migrationReady || !providerConfigured ? <Card className="border-[var(--warning)]"><CardHeader><CardTitle>Configuration technique requise</CardTitle><CardDescription>{!migrationReady ? "La migration du canal email doit encore être appliquée à la base de production." : "Le domaine de réception et les secrets du fournisseur email doivent être configurés avant l’activation en production."}</CardDescription></CardHeader></Card> : null}
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><MailCheck className="text-primary" />{messages.address}</CardTitle><CardDescription>Créez une règle de transfert depuis votre boîte professionnelle vers cette adresse. Ne transférez jamais toute la messagerie.</CardDescription></CardHeader><CardContent>{address ? <div className="flex flex-wrap items-center gap-3 rounded-[var(--radius-lg)] border bg-[var(--glass)] p-4"><code className="min-w-0 flex-1 break-all font-semibold">{address}</code><Copy className="size-4 text-muted-foreground" aria-hidden="true" /></div> : <p className="text-sm text-muted-foreground">L’adresse sera créée lors de l’activation.</p>}</CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Protection des données</CardTitle><CardDescription>{messages.privacy}</CardDescription></CardHeader><CardContent className="grid gap-3 text-sm">{["Webhook signé et vérifié", "Isolation stricte par organisation", "Aucun accès administrateur automatique au contenu", "Faits IA proposés, jamais confirmés automatiquement"].map(item => <p key={item} className="flex gap-2"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" />{item}</p>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Activation contrôlée</CardTitle><CardDescription>{active ? "Le canal accepte les demandes transférées." : messages.inactive}</CardDescription></CardHeader><CardContent><form action={configureEmailChannelAction.bind(null, organizationSlug)} className="grid gap-4"><input type="hidden" name="enabled" value={active ? "false" : "true"} /><label className="grid gap-2 text-sm font-semibold">Conservation des métadonnées techniques<select name="retentionDays" defaultValue={String(channel?.retention_days ?? 90)} className="h-11 rounded-[var(--radius-md)] border bg-background px-3"><option value="30">30 jours</option><option value="90">90 jours</option><option value="180">180 jours</option><option value="365">365 jours</option></select></label>{!active ? <label className="flex items-start gap-3 rounded-[var(--radius-lg)] border p-4 text-sm"><input required type="checkbox" name="acknowledge" className="mt-1 size-4" /><span>{messages.legal}</span></label> : <input type="hidden" name="acknowledge" value="on" />}<Button type="submit" variant={active ? "destructive" : "default"} disabled={!migrationReady || !providerConfigured}>{active ? "Désactiver le canal" : "Activer le canal email"}</Button></form></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><LockKeyhole className="text-primary" />Parcours appliqué</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-5">{["Email transféré", "Dossier créé", "Analyse IA", "Manques identifiés", "Validation humaine"].map((step,index)=><div key={step} className="rounded-[var(--radius-lg)] border p-4"><CheckCircle2 className="size-5 text-primary" /><p className="mt-3 text-xs font-bold uppercase tracking-wide text-muted-foreground">Étape {index+1}</p><p className="mt-1 font-semibold">{step}</p></div>)}</CardContent></Card>
  </main>;
}
