import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Download } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { formatOrganizationDate } from "@/config/i18n";
import { ServiceRequestActions } from "@/features/service-requests/components/service-request-actions";
import { ServiceRequestForm } from "@/features/service-requests/components/service-request-form";
import { serviceRequestMessages as messages } from "@/features/service-requests/messages";
import { canArchiveServiceRequest, canAssignServiceRequest, canDeleteServiceRequest, canExportServiceRequest, canRestoreServiceRequest, canUpdateServiceRequest } from "@/features/service-requests/permissions";
import { serviceRequestReferenceSchema } from "@/features/service-requests/schemas";
import { updateServiceRequestAction } from "@/server/actions/service-requests";
import { getServiceRequestForOrganization, getServiceRequestHistory } from "@/server/service-requests/service";

export default async function ServiceRequestDetailPage({params}:{params:Promise<{organizationSlug:string;reference:string}>}){
  const {organizationSlug,reference:rawReference}=await params;const parsedReference=serviceRequestReferenceSchema.safeParse(rawReference);if(!parsedReference.success)notFound();const reference=parsedReference.data;const {context,detail,members}=await getServiceRequestForOrganization(organizationSlug,reference);const history=await getServiceRequestHistory(context.organization.id,detail.id);const ownership={createdBy:detail.createdBy,assignedUserId:detail.assignedUserId};const canUpdate=canUpdateServiceRequest(context.role,context.userId,ownership);
  return <main className="mx-auto grid w-full max-w-[var(--content-max)] gap-6 p-4 sm:p-8"><PageHeader eyebrow={<Button asChild variant="link"><Link href={`/app/${organizationSlug}/dossiers`}><ArrowLeft/>Tous les Dossiers</Link></Button>} title={detail.title} description={`${detail.referenceCode} · créé le ${formatOrganizationDate(detail.createdAt,context.organization.locale,context.organization.timezone)}`} actions={canExportServiceRequest(context.role)?<Button asChild variant="outline"><Link href={`/app/${organizationSlug}/dossiers/${reference}/export`}><Download/>Exporter en JSON</Link></Button>:undefined}/>
    <div className="flex flex-wrap gap-2"><Badge variant={detail.status==="closed"?"neutral":detail.status==="incomplete"||detail.status==="needs_review"?"warning":"success"}>{messages.statuses[detail.status]}</Badge>{detail.archivedAt?<Badge>Archivé</Badge>:null}<Badge>{detail.assigneeName??"Non attribué"}</Badge></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><div className="grid gap-6"><Card className="hover:translate-y-0"><CardHeader><CardTitle>Demande</CardTitle><CardDescription>Source : saisie manuelle</CardDescription></CardHeader><CardContent className="grid gap-4"><div><p className="text-xs font-semibold text-muted-foreground">Service</p><p>{detail.serviceLabel}</p></div><div><p className="text-xs font-semibold text-muted-foreground">Demande originale</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{detail.originalRequest}</p></div></CardContent></Card>
      <div className="grid gap-6 lg:grid-cols-2"><Card className="hover:translate-y-0"><CardHeader><CardTitle>Demandeur</CardTitle></CardHeader><CardContent><dl className="grid gap-3 text-sm"><div><dt className="text-muted-foreground">Nom</dt><dd>{[detail.requesterFirstName,detail.requesterLastName].filter(Boolean).join(" ")||"—"}</dd></div><div><dt className="text-muted-foreground">Email</dt><dd>{detail.requesterEmail??"—"}</dd></div><div><dt className="text-muted-foreground">Téléphone</dt><dd>{detail.requesterPhone??"—"}</dd></div><div><dt className="text-muted-foreground">Canal préféré</dt><dd>{messages.channels[detail.preferredContactChannel]}</dd></div></dl></CardContent></Card><Card className="hover:translate-y-0"><CardHeader><CardTitle>Localisation</CardTitle></CardHeader><CardContent><address className="text-sm not-italic leading-6">{detail.addressLine1?<>{detail.addressLine1}<br/></>:null}{detail.postalCode} {detail.city}<br/>{detail.countryCode}</address></CardContent></Card></div>
      {canUpdate?<Card className="hover:translate-y-0"><CardHeader><CardTitle>Modifier le Dossier</CardTitle><CardDescription>La version {detail.lockVersion} sera vérifiée avant toute écriture.</CardDescription></CardHeader><CardContent><ServiceRequestForm action={updateServiceRequestAction.bind(null,organizationSlug,reference)} defaults={{title:detail.title,serviceLabel:detail.serviceLabel,originalRequest:detail.originalRequest,requesterFirstName:detail.requesterFirstName,requesterLastName:detail.requesterLastName,requesterEmail:detail.requesterEmail,requesterPhone:detail.requesterPhone,preferredContactChannel:detail.preferredContactChannel,requesterLocale:detail.requesterLocale,countryCode:detail.countryCode,postalCode:detail.postalCode,city:detail.city,addressLine1:detail.addressLine1,lockVersion:detail.lockVersion}} submitLabel="Enregistrer les modifications"/></CardContent></Card>:null}
      <Card className="hover:translate-y-0"><CardHeader><CardTitle>Historique</CardTitle><CardDescription>Événements minimisés, sans copie des coordonnées ni de la demande.</CardDescription></CardHeader><CardContent><ol className="grid gap-3">{history.map(event=><li key={event.id} className="border-l-2 border-primary/25 pl-4"><p className="text-sm font-semibold">{messages.events[event.event_type]}</p><p className="text-xs text-muted-foreground">{formatOrganizationDate(event.created_at,context.organization.locale,context.organization.timezone)}{event.event_type==="status_changed"&&typeof event.metadata==="object"&&event.metadata&&!Array.isArray(event.metadata)?` · ${String(event.metadata.from)} → ${String(event.metadata.to)}`:""}</p></li>)}</ol></CardContent></Card>
      <Card className="border-dashed bg-muted/25 hover:translate-y-0"><CardContent className="pt-5 text-sm text-muted-foreground sm:pt-6">{messages.future}</CardContent></Card></div>
      <Card className="h-fit hover:translate-y-0 xl:sticky xl:top-24"><CardContent className="pt-5 sm:pt-6"><ServiceRequestActions slug={organizationSlug} reference={reference} status={detail.status} lockVersion={detail.lockVersion} members={members} canAssign={canAssignServiceRequest(context.role)} canArchive={canArchiveServiceRequest(context.role,context.userId,ownership)} canRestore={canRestoreServiceRequest(context.role)} canDelete={canDeleteServiceRequest(context.role)} archived={Boolean(detail.archivedAt)}/></CardContent></Card></div>
  </main>;
}
