import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,LockKeyhole} from "lucide-react";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Field,Textarea} from "@/components/ui/input";
import {PageHeader} from "@/components/ui/page-header";
import {PlaybookActionForm} from "@/features/playbooks/components/action-form";
import {demoFieldsText,demoProofsText} from "@/features/playbooks/demo";
import {canManagePlaybooks} from "@/features/playbooks/permissions";
import {createPlaybookVersionAction,publishPlaybookAction,updatePlaybookDraftAction} from "@/server/actions/playbooks";
import {getPlaybook} from "@/server/playbooks/service";

export default async function PlaybookDetailPage({params}:{params:Promise<{organizationSlug:string;playbookId:string}>}){const {organizationSlug,playbookId}=await params;if(!/^[0-9a-f-]{36}$/i.test(playbookId))notFound();const data=await getPlaybook(organizationSlug,playbookId);const canManage=canManagePlaybooks(data.context.role);const draft=data.versions.find(version=>version.status==="draft");return <main className="mx-auto grid w-full max-w-[var(--content-max)] gap-6 p-4 sm:p-8"><PageHeader eyebrow={<Button asChild variant="link"><Link href={`/app/${organizationSlug}/playbooks`}><ArrowLeft/>Tous les Playbooks</Link></Button>} title={data.playbook.name} description={data.playbook.description??"Playbook configurable"}/>
  <div className="grid gap-6 xl:grid-cols-[1fr_20rem]"><div className="grid gap-6">{draft&&canManage?<Card className="hover:translate-y-0"><CardHeader><CardTitle>Éditeur — version {draft.version_number}</CardTitle><CardDescription>Une ligne par champ : clé | libellé | type | oui/non | question. Une preuve : clé | libellé | minimum.</CardDescription></CardHeader><CardContent><PlaybookActionForm action={updatePlaybookDraftAction.bind(null,organizationSlug,playbookId)} label="Enregistrer le brouillon"><input type="hidden" name="versionId" value={draft.id}/><input type="hidden" name="lockVersion" value={draft.lock_version}/><Field label="Champs"><Textarea name="fields" className="min-h-80 font-mono text-xs" defaultValue={draft.schema.fields.map(field=>`${field.key}|${field.label}|${field.type}|${field.required?"oui":"non"}|${field.question}`).join("\n")||demoFieldsText}/></Field><Field label="Preuves"><Textarea name="proofs" className="min-h-24 font-mono text-xs" defaultValue={draft.schema.proofs.map(proof=>`${proof.key}|${proof.label}|${proof.minimum}`).join("\n")||demoProofsText}/></Field><Field label="Action finale"><Textarea name="nextAction" defaultValue={draft.schema.nextAction}/></Field></PlaybookActionForm><div className="mt-6 border-t pt-6"><PlaybookActionForm action={publishPlaybookAction.bind(null,organizationSlug,playbookId)} label="Publier cette version" variant="outline"><input type="hidden" name="versionId" value={draft.id}/><p className="text-sm text-muted-foreground">La publication rend la version définitivement immuable.</p></PlaybookActionForm></div></CardContent></Card>:null}
  {!draft&&canManage&&data.playbook.status==="active"?<Card className="hover:translate-y-0"><CardContent className="pt-6"><PlaybookActionForm action={createPlaybookVersionAction.bind(null,organizationSlug,playbookId)} label="Créer une nouvelle version"><p className="text-sm text-muted-foreground">Le nouveau brouillon copie la version active ; les Dossiers existants conserveront leur version.</p></PlaybookActionForm></CardContent></Card>:null}
  {data.versions.filter(version=>version.status==="published").map(version=><Card key={version.id} className="hover:translate-y-0"><CardHeader><div className="flex items-center justify-between"><CardTitle>Version {version.version_number}</CardTitle><Badge variant="success"><LockKeyhole className="size-3"/>Publiée</Badge></div><CardDescription>{version.published_at?`Publiée le ${new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium"}).format(new Date(version.published_at))}`:"Version active"}</CardDescription></CardHeader><CardContent><p className="text-sm">{version.schema.fields.length} champs · {version.schema.proofs.length} preuve(s)</p><p className="mt-2 text-sm text-muted-foreground">Action : {version.schema.nextAction}</p></CardContent></Card>)}</div>
  <Card className="h-fit hover:translate-y-0"><CardHeader><CardTitle>Versions</CardTitle></CardHeader><CardContent><ol className="grid gap-3">{data.versions.map(version=><li key={version.id} className="flex items-center justify-between gap-2 text-sm"><span>Version {version.version_number}</span><Badge variant={version.status==="published"?"success":"neutral"}>{version.status}</Badge></li>)}</ol></CardContent></Card></div></main>;}
